FROM nginx

#remove default conf file, create directories for static, media and ssl certificate
RUN rm /etc/nginx/conf.d/default.conf \
&& mkdir -p /usr/share/nginx/static \
&& mkdir -p /usr/share/nginx/media \
&& mkdir -p /usr/share/nginx/ssl


# copy config file 
ADD nginx.conf /etc/nginx/conf.d

#grand read and write authority to media file
RUN chmod -R 775 /usr/share/nginx/media


#close daemon mode
CMD ["nginx", "-g", "daemon off;"]
